version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - 1433:1433
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        pid=$$!
        sleep 10s
        /opt/mssql-tools/bin/sqlcmd -S db -U SA -P YourStrong!Passw0rd -Q "CREATE DATABASE SchemaRegistry"
        wait $$pid